// Offline test of the records panel's rules (src/records_rules.h) and its text
// (src/records_text.h, generated by tools/gen_records.py):
//
//   x86_64-w64-mingw32-g++ -std=c++20 -O2 -static tests/test_records.cpp -o tests/build/test_records.exe
//   wine tests/build/test_records.exe
//
// The rules are what switching a record on or off writes, checked against the
// game's own check (RecordManager.checkClearedRecord, RogueRecordManager.
// checkClearedRogueRecord_Simple, RogueRecordManager.get_IsOpenedScenarioD) as
// records_rules.h restates them: a record switched on must pass it, one switched
// off must fail it - and No Way Out must never close.
#include <cstdio>
#include <cstring>

#include "../src/records_rules.h"
#include "../src/records_text.h"

namespace {

using namespace re2cc::records;

int g_fail = 0;

void check(bool ok, const char* what) {
  std::printf("%s  %s\n", ok ? "ok  " : "FAIL", what);
  if (!ok) ++g_fail;
}

// The game's check for The Ghost Survivors, as the code reads (see records_rules.h).
bool rogue_earned(const rules::RogueTypes& t, int type, int scenario, int goal, rules::Counted counted,
                  const rules::RogueSave& s) {
  if (type == t.clear_normal) return s.normal[scenario];
  if (type == t.clear_training) return s.training[scenario] || s.normal[scenario];
  if (type == t.special) return s.special[scenario];
  if (type == t.count_up) return counted == rules::kPlays ? s.plays >= goal : counted == rules::kRaccoons && s.raccoons >= goal;
  return false;
}

}  // namespace

int main() {
  char what[256];

  // --- the main game's progress numbers --------------------------------------------------------------------
  const rules::ProgressTypes pt;  // this build: NONE 0, COUNT_UP 1, COUNT_DOWN 2; the rest (3..7) exactly
  check(rules::kind_of(pt, 0) == rules::kAtLeast && rules::kind_of(pt, 1) == rules::kAtLeast &&
            rules::kind_of(pt, 2) == rules::kWithin && rules::kind_of(pt, 3) == rules::kExactly &&
            rules::kind_of(pt, 7) == rules::kExactly,
        "ProgressType kinds: NONE/COUNT_UP at least, COUNT_DOWN within, CLEARTIME..ADA_GUN exactly");
  struct Case {
    rules::Kind kind;
    int progress, goal;
  };
  const Case cases[] = {{rules::kAtLeast, 0, 1},   {rules::kAtLeast, 1, 1},    {rules::kAtLeast, 3, 10},
                        {rules::kAtLeast, 10, 10}, {rules::kAtLeast, 250, 10}, {rules::kAtLeast, 2, 2},
                        {rules::kWithin, 0, 13},   {rules::kWithin, 9, 13},    {rules::kWithin, 13, 13},
                        {rules::kWithin, 20, 13},  {rules::kExactly, 0, 3},    {rules::kExactly, 3, 3},
                        {rules::kExactly, 0, 14000}, {rules::kExactly, 14000, 14000}, {rules::kAtLeast, -1, 5}};
  int bad_on = 0, bad_off = 0, lost = 0;
  for (const Case& c : cases) {
    const int on = rules::on_progress(c.kind, c.progress, c.goal);
    const int off = rules::off_progress(c.kind, c.progress, c.goal);
    if (!rules::meets(c.kind, on, c.goal)) ++bad_on;
    if (rules::meets(c.kind, off, c.goal)) ++bad_off;
    // What earned it already is kept switching on; a count kept as close as it can be switching off.
    if (rules::meets(c.kind, c.progress, c.goal) && on != c.progress) ++lost;
    if (!rules::meets(c.kind, c.progress, c.goal) && off != c.progress) ++lost;
  }
  std::snprintf(what, sizeof(what), "on earns, off un-earns, by the game's check: %d/%d wrong, %d changed needlessly",
                bad_on, bad_off, lost);
  check(!bad_on && !bad_off && !lost, what);
  check(rules::on_progress(rules::kAtLeast, 3, 10) == 10 && rules::off_progress(rules::kAtLeast, 250, 10) == 9,
        "a kill count: on puts it at the goal, off just short of it (one more kill earns it)");
  check(rules::on_progress(rules::kWithin, 9, 13) == 9 && rules::on_progress(rules::kWithin, 0, 13) == 13 &&
            rules::off_progress(rules::kWithin, 9, 13) == 0,
        "a puzzle's moves: a better score is kept, none becomes the goal; off is 0 (never done)");
  check(rules::off_progress(rules::kExactly, 14000, 14000) == 0 && rules::on_progress(rules::kExactly, 12, 14000) == 14000,
        "an end-of-game record: exactly its goal on, 0 off");

  // Rewards shared: only the tofu survivors (RECORD_090 and _091 both give OPEN_MODE_06 and _07).
  {
    bool cleared[3] = {true, true, false};
    const int rewards[3 * 4] = {7, 8, -1, -1, /*091*/ 9, 10, 7, 8, /*other*/ 55, -1, -1, -1};
    check(rules::granted_elsewhere(7, 0, cleared, rewards, 3, 4) && !rules::granted_elsewhere(9, 1, cleared, rewards, 3, 4),
          "a reward another cleared record gives stays; one no other gives goes");
    cleared[1] = false;
    check(!rules::granted_elsewhere(7, 0, cleared, rewards, 3, 4), "a reward only an uncleared record gives goes");
  }

  // Mr. Raccoons: the last ones broken come back first, down to what the record allows.
  {
    bool broken[15];
    for (bool& b : broken) b = true;
    check(rules::unbreak_to(broken, 15, 14) == 1 && !broken[14] && broken[13], "all 15 broken, 14 kept: the last one back");
    check(rules::unbreak_to(broken, 15, 9) == 5 && !broken[9] && broken[8], "down to 9: five more back");
    check(rules::unbreak_to(broken, 15, 9) == 0, "already at 9: nothing");
  }

  // --- The Ghost Survivors ---------------------------------------------------------------------------------------
  // This build's table (RogueRecordUserData): type, scenario, goal, what it counts.
  const rules::RogueTypes rt;
  struct Rec {
    int type, scenario, goal;
    rules::Counted counted;
  };
  const Rec rec[15] = {{3, 0, 3, rules::kPlays},   {1, 0, 1, rules::kNotCounted}, {1, 1, 1, rules::kNotCounted},
                       {1, 2, 1, rules::kNotCounted}, {1, 3, 1, rules::kNotCounted}, {3, 0, 10, rules::kPlays},
                       {0, 0, 1, rules::kNotCounted}, {2, 0, 1, rules::kNotCounted}, {0, 1, 1, rules::kNotCounted},
                       {2, 1, 1, rules::kNotCounted}, {0, 2, 1, rules::kNotCounted}, {2, 2, 1, rules::kNotCounted},
                       {0, 3, 1, rules::kNotCounted}, {2, 3, 1, rules::kNotCounted}, {3, 0, 10, rules::kRaccoons}};
  // Every record, from every one of a set of saves: on earns it; off either un-earns it or holds it - and
  // never closes No Way Out, and holds only while No Way Out is open.
  int bad = 0, closed = 0, needless_holds = 0, held = 0, tried = 0;
  for (int mask = 0; mask < (1 << 8); ++mask) {
    rules::RogueSave base;
    for (int t = 0; t < 4; ++t) {
      base.normal[t] = mask & (1 << t);
      base.training[t] = mask & (1 << (t + 4));
    }
    base.plays = mask % 12;
    base.raccoons = 10;
    base.special[2] = base.route_c[0] = base.route_c[1] = true;
    for (int id = 0; id < 15; ++id) {
      const Rec& r = rec[id];
      rules::RogueSave on = base;
      rules::rogue_on(rt, r.type, r.scenario, r.goal, r.counted, &on);
      if (!rogue_earned(rt, r.type, r.scenario, r.goal, r.counted, on)) ++bad;
      if (rules::no_way_out_open(base) && !rules::no_way_out_open(on)) ++closed;
      rules::RogueSave off = base;
      const bool hold = rules::rogue_off(rt, r.type, r.scenario, r.goal, r.counted, &off);
      if (r.counted == rules::kRaccoons) off.raccoons = r.goal - 1;  // the caller's unbreak_to
      // A held record's node says COUNT_UP; the check counts only the counted ones.
      if (hold && !rules::can_hold(rt, r.type, r.scenario, r.counted)) ++bad;
      const int type = hold ? rt.count_up : r.type;
      if (rogue_earned(rt, type, r.scenario, r.goal, r.counted, off)) ++bad;
      if (rules::no_way_out_open(base) && !rules::no_way_out_open(off)) ++closed;
      if (hold && !rules::no_way_out_open(base)) ++needless_holds;
      held += hold;
      ++tried;
    }
  }
  std::snprintf(what, sizeof(what),
                "Ghost Survivors, %d switches from 256 saves: %d wrong, No Way Out closed %d times, %d needless holds "
                "(%d held)",
                tried * 2, bad, closed, needless_holds, held);
  check(!bad && !closed && !needless_holds && held > 0, what);
  {
    rules::RogueSave s;
    s.normal[0] = true;  // Forgotten Soldier cleared on normal only; B and C by training: No Way Out open
    s.training[1] = s.training[2] = true;
    check(rules::no_way_out_open(s), "No Way Out: A, B, C cleared either way");
    rules::RogueSave off = s;
    check(!rules::rogue_off(rt, 0, 0, 1, rules::kNotCounted, &off) && !off.normal[0] && off.training[0] &&
              rules::no_way_out_open(off),
          "\"The Ghost Who Lived\" off: the normal clear becomes a training clear, No Way Out stays open");
    off = s;
    check(rules::rogue_off(rt, 1, 0, 1, rules::kNotCounted, &off) && off.normal[0],
          "\"Mission Complete?\" off while No Way Out is open: held, the scenario left cleared");
    rules::RogueSave closed_d = s;
    closed_d.training[2] = false;  // C not cleared: No Way Out shut already
    off = closed_d;
    check(!rules::rogue_off(rt, 1, 0, 1, rules::kNotCounted, &off) && !off.normal[0] && !off.training[0],
          "\"Mission Complete?\" off while No Way Out is shut anyway: the scenario is un-cleared (earn it again)");
    rules::RogueSave on;
    rules::rogue_on(rt, 1, 3, 1, rules::kNotCounted, &on);
    check(on.training[3] && !on.normal[3], "\"1st Survivor\" on: a training clear, which does not earn \"Hell of a Sheriff\"");
    rules::RogueSave c;
    rules::rogue_on(rt, 2, 2, 1, rules::kNotCounted, &c);
    check(c.special[2] && c.route_c[0] && c.route_c[1], "\"Sewer Explorer\" on: both routes taken");
    rules::rogue_off(rt, 2, 2, 1, rules::kNotCounted, &c);
    check(!c.special[2] && !c.route_c[0] && !c.route_c[1], "\"Sewer Explorer\" off: both routes forgotten");
    rules::RogueSave p;
    p.plays = 12;
    rules::rogue_off(rt, 3, 0, 3, rules::kPlays, &p);
    check(p.plays == 2, "\"Warm Up Complete\" off: 12 plays become 2");
  }
  check(rules::can_hold(rt, 1, 0, rules::kNotCounted) && rules::can_hold(rt, 1, 2, rules::kNotCounted) &&
            !rules::can_hold(rt, 1, 3, rules::kNotCounted) && !rules::can_hold(rt, 0, 0, rules::kNotCounted) &&
            !rules::can_hold(rt, 3, 0, rules::kPlays),
        "only the A-C cleared-either-way records are ever held (as COUNT_UP, which the check does not count for them)");

  // --- the generated text ------------------------------------------------------------------------------------------
  namespace rt_ = re2cc::records_text;
  int named = 0;
  for (const auto& r : rt_::kRecord) named += r.name != nullptr;
  std::snprintf(what, sizeof(what), "%d of %d main records named (the 4 hidden ones are not)", named, rt_::kRecords);
  check(rt_::kRecords == 91 && named == 87, what);
  check(rt_::kRecord[0].name && !std::strcmp(rt_::kRecord[0].name, "Raccoon City Native"), "RECORD_001 is Raccoon City Native");
  volatile int k20 = 19;  // RECORD_020 (a runtime index: GCC folds a constant one and warns)
  check(rt_::kRecord[k20].condition && std::strstr(rt_::kRecord[k20].condition, "{0}"), "RECORD_020's condition has {0}");
  check(rt_::kRogueRecords == 15 && rt_::kRogueRecord[1].name && !std::strcmp(rt_::kRogueRecord[1].name, "Mission Complete?") &&
            rt_::kRogueRecord[12].name && !std::strcmp(rt_::kRogueRecord[12].name, "Hell of a Sheriff") &&
            rt_::kRogueRecord[14].name && !std::strcmp(rt_::kRogueRecord[14].name, "Got 'Em"),
        "Ghost Survivors records named by id (01 Mission Complete?, 12 Hell of a Sheriff, 14 Got 'Em)");
  check(rt_::kAccessory[14] && std::strstr(rt_::kAccessory[14], "Cat Ears"), "ACCESSORY_14 is Cat Ears");
  bool sorted = true;
  constexpr size_t kN = sizeof(rt_::kRewardText) / sizeof(rt_::kRewardText[0]);
  for (size_t i = 1; i < kN; ++i) {
    const auto &a = rt_::kRewardText[i - 1], &b = rt_::kRewardText[i];
    sorted = sorted && (a.hi < b.hi || (a.hi == b.hi && a.lo < b.lo));
  }
  std::snprintf(what, sizeof(what), "%zu reward texts, sorted by GUID for the lookup", kN);
  check(kN > 100 && sorted, what);
  bool ascii_ok = true;
  auto latin1_utf8 = [](const char* s) {
    for (const unsigned char* p = reinterpret_cast<const unsigned char*>(s); p && *p; ++p)
      if (*p >= 0x80 && *p != 0xC2 && *p != 0xC3 && (*p < 0x80 || *p > 0xBF)) return false;
    return true;
  };
  for (const auto& r : rt_::kRecord) ascii_ok = ascii_ok && latin1_utf8(r.name) && latin1_utf8(r.condition);
  for (size_t i = 0; i < kN; ++i) ascii_ok = ascii_ok && latin1_utf8(rt_::kRewardText[i].text);
  check(ascii_ok, "every text is Latin-1 in UTF-8 (the panel's font has those glyphs)");

  std::printf("%s: %d failure(s)\n", g_fail ? "FAILED" : "PASSED", g_fail);
  return g_fail ? 1 : 0;
}
