#pragma once

#include <cstdint>

// Generated by tools/gen_records.py from the game's record tables and its English text - do not
// edit by hand. The records panel's names: the main records by RecordId, The Ghost Survivors'
// records by RogueRecordId and their accessories by RogueRewardId, and the rewards' names by the
// message GUID RecordManager gives each RewardNode. "{0}" in a condition is the record's goal.
namespace re2cc::records_text {

struct Record {
  const char* name;       // nullptr: the game has none (a hidden record)
  const char* condition;
};

inline constexpr int kRecords = 91;  // RecordManager.RecordId.MAX
inline constexpr Record kRecord[kRecords] = {
    {"Raccoon City Native", "Complete all objectives in Records."},  // RECORD_001
    {"Welcome to the City of the Dead", "Make it to the police station."},  // RECORD_002
    {"Path to the Goddess", "Solve the Goddess Statue puzzle."},  // RECORD_003
    {"Never-Ending Rain", "Escape the police station."},  // RECORD_004
    {"Hack Complete", "Complete Ada's segment."},  // RECORD_005
    {"Hide and Seek", "Complete Sherry's segment."},  // RECORD_006
    {"A Great Need for a Shower", "Escape from the sewers."},  // RECORD_007
    {"Survival", "Escape the lab."},  // RECORD_008
    {"A Hero Emerges", "Complete Leon's story."},  // RECORD_009
    {"A Heroine Emerges", "Complete Claire's story."},  // RECORD_010
    {"Broken Umbrella", "Witness the true ending."},  // RECORD_011
    {"The Basics of Survival", "Combine two items together."},  // RECORD_012
    {"First Break-In", "Open a dial safe."},  // RECORD_013
    {"A Vault-like Mind", "Open a portable safe."},  // RECORD_014
    {"Vermin Extermination", "Destroy a Mr. Raccoon."},  // RECORD_015
    {"Customizer", "Customize a weapon."},  // RECORD_016
    {"Hip to Add Squares", "Increase your inventory slots."},  // RECORD_017
    {"Eat This!", "Counterattack with a sub-weapon."},  // RECORD_018
    {"That'll Hold 'Em", "Use Wooden Boards to board up a window."},  // RECORD_019
    {"Handy with a Handgun", "Kill {0} enemies with a handgun."},  // RECORD_020
    {"Matter of Splatter", "Kill {0} enemies with a shotgun."},  // RECORD_021
    {"Trigger Happy", "Kill {0} enemies with a submachine gun."},  // RECORD_022
    {"Got a Problem, Punk?", "Kill {0} enemies with a MAG."},  // RECORD_023
    {"You Die...Over There!", "Kill {0} enemies with the grenade launcher."},  // RECORD_024
    {"Human Power Plant", "Kill {0} enemies with the Spark Shot."},  // RECORD_025
    {"Bring Marshmallows!", "Kill {0} enemies with the Chemical Flamethrower."},  // RECORD_026
    {"Master Tactician", "Kill {0} enemies with a sub-weapon."},  // RECORD_027
    {"Don't Need No Stinkin' Gun", "Defeat an enemy with a knife."},  // RECORD_028
    {"But a Torso", "Destroy the arms and legs of a zombie."},  // RECORD_029
    {"Bon Appétit", "Shoot the grenade you fed to an enemy."},  // RECORD_030
    {"A Doff of the Cap", "Shoot a hat off of {0} zombies' heads."},  // RECORD_031
    {"Like Skeet Shooting", "Shoot a zombie dog or a licker out of the air."},  // RECORD_032
    {"Keep Their Heads Ringin'", "Paralyze a licker's sense of hearing."},  // RECORD_033
    {"Two Birds, One Stone", "Kill two enemies at once with a single bullet/shotgun blast."},  // RECORD_034
    {"Hate to Burst Your Bulb", "Immobilize an ivy zombie by shooting only its bulbs."},  // RECORD_035
    {"A Shocking End", "Fire a Maximum Discharge by charging the Spark Shot to max."},  // RECORD_036
    {"Zombie Roundup", "Kill {0} enemies at once with a sub-weapon."},  // RECORD_037
    {"Hats Off!", "Shoot Tyrant's hat off his head."},  // RECORD_038
    {"Take a Breather", "Bring Tyrant down to one knee."},  // RECORD_039
    {"Circuit Breaker", "Open the Jail's electronic cell door in {0} moves. [Leon's story]"},  // RECORD_040
    {"Voltage Virtuoso", "Open the Private Collection Room's electronic door in {0} moves. [Claire's story]"},  // RECORD_041
    {"Hardly Any Resistance", "Open the Jail's electronic cell door in {0} moves. [Leon's 2nd Run story]"},  // RECORD_042
    {"A Jewel Amongst Joules", "Open the Private Collection Room's electronic door in {0} moves. [Claire's 2nd Run story]"},  // RECORD_043
    {"Chemist", "Fill the cartridge in the Drug Testing Lab in {0} moves. [Either Leon's or Claire's story]"},  // RECORD_044
    {"Genius Chemist", "Fill the cartridge in the Drug Testing Lab in {0} moves. [Either Leon's or Claire's 2nd Run story]"},  // RECORD_045
    {"Right in the Eyeball", "Stab Stage 1 G in the giant eyeball with a knife."},  // RECORD_046
    {"Gotcha!", "Defeat Stage 2 G using the crane only once."},  // RECORD_047
    {"Put that Down!", "Stop Stage 3 G from throwing things around."},  // RECORD_048
    {"You Belong on the Ground", "Shoot Stage 4 G down off of a wall."},  // RECORD_049
    {"With Time to Spare", "Defeat Stage 4 G with {0}+ minutes left until detonation."},  // RECORD_050
    {"Maxed Out", "Stop Super Tyrant from charging."},  // RECORD_051
    {"In the Blink of an Eye", "Defeat Super Tyrant with {0}+ minutes left until detonation."},  // RECORD_052
    {"One Slick Super-spy", "Use only the EMF Visualizer to complete Ada's gameplay segment."},  // RECORD_053
    {"Young Escapee", "Escape the bedroom within {0} seconds during Sherry's segment."},  // RECORD_054
    {"Master of Unlocking", "Open all of the safes and locks in the game."},  // RECORD_055
    {"Complete Vermin Extermination", "Destroy all Mr. Raccoons."},  // RECORD_056
    {"Lore Explorer", "Read all of the files."},  // RECORD_057
    {"Dark Times, Dark Room", "Develop all rolls of film."},  // RECORD_058
    {"Treasure Hunter", "Using the photo hints, find 2 hidden items."},  // RECORD_059
    {"A Waist of Space", "Expand inventory slots to max."},  // RECORD_060
    {"Packed Pockets", "Obtain all of the custom parts in Leon's story."},  // RECORD_061
    {"Packed Backpack", "Obtain all of the custom parts in Claire's story."},  // RECORD_062
    {"Gun Fanatic", "Obtain all of the weapons in Leon's story."},  // RECORD_063
    {"Gun Enthusiast", "Obtain all of the weapons in Claire's story."},  // RECORD_064
    {"Hardcore Rookie", "Complete Leon's story on \"Hardcore\" game mode."},  // RECORD_065
    {"Hardcore College Student", "Complete Claire's story on \"Hardcore\" game mode."},  // RECORD_066
    {"Leon \"A.\" Kennedy", "Complete Leon's story on \"Standard\" or \"Hardcore\" with an A rank."},  // RECORD_067
    {"Courageous Crimson Hero", "Complete Claire's story on \"Standard\" or \"Hardcore\" with an A rank."},  // RECORD_068
    {"Leon \"S.\" Kennedy", "Complete Leon's story on \"Standard\" or \"Hardcore\" with an S rank."},  // RECORD_069
    {"Sizzling Scarlet Hero", "Complete Claire's story on \"Standard\" or \"Hardcore\" with an S rank."},  // RECORD_070
    {"Rookie No More", "Complete Leon's story on \"Hardcore\" with an S rank."},  // RECORD_071
    {"The Redfield Way", "Complete Claire's story on \"Hardcore\" with an S rank."},  // RECORD_072
    {"Sprinter", "Complete the game within {0} hours."},  // RECORD_073
    {"Minimalist", "Clear the game without opening the item box."},  // RECORD_074
    {"Frugalist", "Complete the game without using a recovery item."},  // RECORD_075
    {"A Small Carbon Footprint", "Take {0} steps or fewer in one playthrough."},  // RECORD_076
    {"Grim Reaper", "Complete \"The 4th Survivor\" extra mode."},  // RECORD_077
    {"That Jiggly Deliciousness", "Complete \"The Tofu Survivor\" extra mode."},  // RECORD_078
    {"An Acquired Taste", "Complete \"The Tofu Survivor\" extra mode with Uiro-Mochi."},  // RECORD_079
    {"Can't Get Enough", "Complete \"The Tofu Survivor\" extra mode with Annin Tofu."},  // RECORD_080
    {"The Perfect Chewiness", "Complete \"The Tofu Survivor\" extra mode with Konjac."},  // RECORD_081
    {"An Exquisite Sweetness", "Complete \"The Tofu Survivor\" extra mode with Flan."},  // RECORD_082
    {"Story Master", "Complete all four stories (Leon/Leon [2nd Run]/Claire/Claire [2nd Run])."},  // RECORD_083
    {"A-rank Player", "Complete the game on \"Standard\" or \"Hardcore\" with an A rank."},  // RECORD_084
    {"S-rank Player", "Complete the game on \"Standard\" or \"Hardcore\" with an S rank."},  // RECORD_085
    {"Hardcore S-rank Player", "Complete the game on \"Hardcore\" with an S rank."},  // RECORD_086
    {nullptr, nullptr},  // RECORD_087
    {nullptr, nullptr},  // RECORD_088
    {"Endangered Species", "Destroy {0} Mr. Raccoons."},  // RECORD_089
    {nullptr, nullptr},  // RECORD_090
    {nullptr, nullptr},  // RECORD_091
};

inline constexpr int kRogueRecords = 15;  // RogueRecordManager.RogueRecordId.MAX
inline constexpr Record kRogueRecord[kRogueRecords] = {
    {"Warm Up Complete", "Play The Ghost Survivors 3 times."},  // ROGUE_RECORD_00
    {"Mission Complete?", "Complete the Forgotten Soldier scenario."},  // ROGUE_RECORD_01
    {"Reunited", "Complete the Runaway scenario."},  // ROGUE_RECORD_02
    {"Getting Over It", "Complete the No Time To Mourn scenario."},  // ROGUE_RECORD_03
    {"1st Survivor", "Complete the No Way Out scenario."},  // ROGUE_RECORD_04
    {"All Nights Dawn", "Play The Ghost Survivors 10 times."},  // ROGUE_RECORD_05
    {"The Ghost Who Lived", "Complete the Forgotten Soldier scenario. (No training mode)"},  // ROGUE_RECORD_06
    {"Cookin' Up A Bomb", "Make a grenade by combining items."},  // ROGUE_RECORD_07
    {"The Power of Love", "Complete the Runaway scenario. (No training mode)"},  // ROGUE_RECORD_08
    {"Mastering Unlocking", "Complete and open all locks in the Runaway scenario. (No training mode)"},  // ROGUE_RECORD_09
    {"The Great Gunsmith", "Complete the No Time To Mourn scenario. (No training mode)"},  // ROGUE_RECORD_10
    {"Sewer Explorer", "Complete the No Time To Mourn scenario with both routes. (No training mode)"},  // ROGUE_RECORD_11
    {"Hell of a Sheriff", "Complete the No Way Out scenario. (No training mode)"},  // ROGUE_RECORD_12
    {"Gunslinger", "Complete the No Way Out scenario without firing more than {0} handgun shots. (No training mode)"},  // ROGUE_RECORD_13
    {"Got 'Em", "Destroy all Mr. Raccoons hidden in The Ghost Survivors mode."},  // ROGUE_RECORD_14
};

inline constexpr const char* kAccessory[kRogueRecords] = {
    "Skull",  // ACCESSORY_00
    "Crocodile",  // ACCESSORY_01
    "Gas Mask",  // ACCESSORY_02
    "Egghead",  // ACCESSORY_03
    "Unicorn",  // ACCESSORY_04
    "Mr. Raccoon",  // ACCESSORY_05
    "Molded",  // ACCESSORY_06
    "G",  // ACCESSORY_07
    "Ivy",  // ACCESSORY_08
    "Tyrant",  // ACCESSORY_09
    "Licker",  // ACCESSORY_10
    "Tiger",  // ACCESSORY_11
    "Sheep",  // ACCESSORY_12
    "Raccoon",  // ACCESSORY_13
    "Cat Ears (infinite ammo)",  // ACCESSORY_14
};

// A message GUID as the game stores a System.Guid: its 16 bytes, read as two little-endian words.
struct Text {
  uint64_t lo, hi;
  const char* text;
};

inline constexpr Text kRewardText[] = {  // sorted by (hi, lo)
    {0x4B1798A456B31EFBULL, 0x02B4D29929A05B97ULL, "Extra Mode - \"The Tofu Survivor\""},  // 56b31efb-98a4-4b17-975b-a02999d2b402
    {0x4244211238CF184FULL, 0x03776718BEC9CE95ULL, "The Tofu Survivor (Flan unlocked)"},  // 38cf184f-2112-4244-95ce-c9be18677703
    {0x4D219B95353CD1B3ULL, 0x04185937A8B63A91ULL, "MQ 11"},  // 353cd1b3-9b95-4d21-913a-b6a837591804
    {0x4F687839A0E7BDC0ULL, 0x054A6F00F2F5F5B1ULL, "Flan"},  // a0e7bdc0-7839-4f68-b1f5-f5f2006f4a05
    {0x4600B9F6E0583557ULL, 0x080DC022F61FA6B5ULL, "Design Sketch B"},  // e0583557-b9f6-4600-b5a6-1ff622c00d08
    {0x416C7EEC49918CEAULL, 0x085DFA1509755BACULL, "Ada (Trench Coat)"},  // 49918cea-7eec-416c-ac5b-750915fa5d08
    {0x400BD813756404F8ULL, 0x091F49EADF130CA6ULL, "Flame Rounds"},  // 756404f8-d813-400b-a60c-13dfea491f09
    {0x433E0F324B218DA5ULL, 0x09C2DEA5B2BAD5A5ULL, "Leon (Classic Custom)"},  // 4b218da5-0f32-433e-a5d5-bab2a5dec209
    {0x497B9CA34C3C2392ULL, 0x0A973489FA52E394ULL, "Storyboards"},  // 4c3c2392-9ca3-497b-94e3-52fa8934970a
    {0x4857EABA21A6A111ULL, 0x0CE877395952BB8DULL, "M19"},  // 21a6a111-eaba-4857-8dbb-52593977e80c
    {0x440D767CD21AD665ULL, 0x0D217A1F49CA8E82ULL, "Robert and Emma Kendo"},  // d21ad665-767c-440d-828e-ca491f7a210d
    {0x40723804F16A6ABEULL, 0x0E10BC9639B4DF94ULL, "Chemical Flamethrower"},  // f16a6abe-3804-4072-94df-b43996bc100e
    {0x48C007175BAF2298ULL, 0x10C965BB10771785ULL, "Quickdraw Army"},  // 5baf2298-0717-48c0-8517-7710bb65c910
    {0x4547C3FD26256708ULL, 0x125399B64C35BAACULL, "Weapons and Items"},  // 26256708-c3fd-4547-acba-354cb6995312
    {0x45F6491B8EE8928FULL, 0x1261554443D9989CULL, "Ben Bertolucci"},  // 8ee8928f-491b-45f6-9c98-d94344556112
    {0x47F7252F4AA22BBDULL, 0x138566F3F64FC592ULL, "Alligator"},  // 4aa22bbd-252f-47f7-92c5-4ff6f3668513
    {0x4279C1DFBD40451AULL, 0x16B0AD0FF3D54E85ULL, "Bonus 3 (Melee)"},  // bd40451a-c1df-4279-854e-d5f30fadb016
    {0x4E693C6A550C1101ULL, 0x173C0EB21BD8B48DULL, "Lightning Hawk"},  // 550c1101-3c6a-4e69-8db4-d81bb20e3c17
    {0x4BFE45DBF7CD1942ULL, 0x17793946598A6483ULL, "Anti-tank Rocket"},  // f7cd1942-45db-4bfe-8364-8a5946397917
    {0x40F294FE0D6EC90CULL, 0x184A15C28D226980ULL, "Annin Tofu"},  // 0d6ec90c-94fe-40f2-8069-228dc2154a18
    {0x4FCB7DD4DB9FEB5FULL, 0x190B760A20CD0AB4ULL, "JMB Hp3"},  // db9feb5f-7dd4-4fcb-b40a-cd200a760b19
    {0x4A8CAD472D899187ULL, 0x1B42CA7796B87DA1ULL, "Police Station B"},  // 2d899187-ad47-4a8c-a17d-b89677ca421b
    {0x49E875D21D9980B2ULL, 0x1C198EEE8E0F4BBFULL, "Anti-tank Rocket"},  // 1d9980b2-75d2-49e8-bf4b-0f8eee8e191c
    {0x4501479D46A59DA0ULL, 0x1CE1E9731AAF47B5ULL, "Survivors"},  // 46a59da0-479d-4501-b547-af1a73e9e11c
    {0x40095FF4ACD4A87DULL, 0x1CE38C7CA100C7A2ULL, "Sherry (School Uniform)"},  // acd4a87d-5ff4-4009-a2c7-00a17c8ce31c
    {0x4098DB8FFD5E356EULL, 0x1D849E5587A5E780ULL, "G (Stage 2)"},  // fd5e356e-db8f-4098-80e7-a587559e841d
    {0x4E303AD5209652E6ULL, 0x1F2014F6DF55BC8CULL, "Anti-tank Rocket"},  // 209652e6-3ad5-4e30-8cbc-55dff614201f
    {0x49335E0F4E2BB292ULL, 0x2090633C57DD5C8AULL, "Ivy"},  // 4e2bb292-5e0f-4933-8a5c-dd573c639020
    {0x4B91B2DD06F4E984ULL, 0x2110DB971487F0B0ULL, "Leon (Casual)"},  // 06f4e984-b2dd-4b91-b0f0-871497db1021
    {0x42F03EEB6519B380ULL, 0x22A977FAEA4F0C99ULL, "The Tofu Survivor (Uiro-Mochi unlocked)"},  // 6519b380-3eeb-42f0-990c-4feafa77a922
    {0x45E0F39853B045B8ULL, 0x2497C5D20E4B878BULL, "Sherry (Classic Jacket)"},  // 53b045b8-f398-45e0-8b87-4b0ed2c59724
    {0x4129A76AC3E358F7ULL, 0x2690FE6B03A5D388ULL, "Combat Knife"},  // c3e358f7-a76a-4129-88d3-a5036bfe9026
    {0x4A86966B77F1A0A9ULL, 0x28EE509E7C499684ULL, "Licker"},  // 77f1a0a9-966b-4a86-8496-497c9e50ee28
    {0x427B9B0FBBBE4A38ULL, 0x2BAEC48038960CA1ULL, "Gun Shop \"Kendo\""},  // bbbe4a38-9b0f-427b-a10c-963880c4ae2b
    {0x4A2BB0442BC3AA5FULL, 0x2F59B33C0C766B82ULL, "Spark Shot"},  // 2bc3aa5f-b044-4a2b-826b-760c3cb3592f
    {0x49BAF4AB1D493DA5ULL, 0x300F20D3E7505092ULL, "MQ 11"},  // 1d493da5-f4ab-49ba-9250-50e7d3200f30
    {0x48FECF93A29972ABULL, 0x303861493A8FD7A8ULL, "Claire (Classic Jacket)"},  // a29972ab-cf93-48fe-a8d7-8f3a49613830
    {0x4BA0FF5E70A545C2ULL, 0x309CDDA96CD1A888ULL, "Claire (Normal Custom)"},  // 70a545c2-ff5e-4ba0-88a8-d16ca9dd9c30
    {0x4C42151C7C5E8A9EULL, 0x32C4B668EB49C08FULL, "Flash Grenade"},  // 7c5e8a9e-151c-4c42-8fc0-49eb68b6c432
    {0x4E58589CCD691DDAULL, 0x3338C6BE0E6E45AFULL, "GM 79"},  // cd691dda-589c-4e58-af45-6e0ebec63833
    {0x421181E1E636E309ULL, 0x350A8F9789E89D84ULL, "Extra Mode - \"The 4th Survivor\""},  // e636e309-81e1-4211-849d-e889978f0a35
    {0x4F30C029F28DBF87ULL, 0x35A415535C83669AULL, "Tyrant"},  // f28dbf87-c029-4f30-9a66-835c5315a435
    {0x4FFED68DFCBF7D16ULL, 0x3689947A0EC86D8DULL, "Brian Irons"},  // fcbf7d16-d68d-4ffe-8d6d-c80e7a948936
    {0x453D96A64511C828ULL, 0x3CBE6233BADB8791ULL, "G-Young"},  // 4511c828-96a6-453d-9187-dbba3362be3c
    {0x4C2FE2F7A6EA7BE5ULL, 0x3E14E74F6D88EDABULL, "Raccoon City C"},  // a6ea7be5-e2f7-4c2f-abed-886d4fe7143e
    {0x424F9A9589C58963ULL, 0x42EDC1BBBD1ACE9FULL, "Police Station A"},  // 89c58963-9a95-424f-9fce-1abdbbc1ed42
    {0x4E2049E0F6597522ULL, 0x43545B06B18505A4ULL, "Minigun"},  // f6597522-49e0-4e20-a405-85b1065b5443
    {0x4C6A7E6C215BD1ADULL, 0x4470322D0B9424BAULL, "Flash Grenade"},  // 215bd1ad-7e6c-4c6a-ba24-940b2d327044
    {0x4E205832684A1861ULL, 0x44F707E1C0F17DBEULL, "Tyrant"},  // 684a1861-5832-4e20-be7d-f1c0e107f744
    {0x4D397789B0919B08ULL, 0x4539DD265E1B4B8AULL, "G (Stage 2)"},  // b0919b08-7789-4d39-8a4b-1b5e26dd3945
    {0x426F5ACBF3EDD4FBULL, 0x48D6C29ECBE27EA4ULL, "Alligator"},  // f3edd4fb-5acb-426f-a47e-e2cb9ec2d648
    {0x4CD56EAB95AE5736ULL, 0x48DEB8B3417183B6ULL, "LE 5"},  // 95ae5736-6eab-4cd5-b683-7141b3b8de48
    {0x417782344705A4F8ULL, 0x49257C4909ABF189ULL, "SLS 60"},  // 4705a4f8-8234-4177-89f1-ab09497c2549
    {0x4347286156320C25ULL, 0x49333B9DFE1606A7ULL, "Zombie (Male)"},  // 56320c25-2861-4347-a706-16fe9d3b3349
    {0x4C34772D048F2D42ULL, 0x4977C6A2CBDA4CA9ULL, "Claire (Tank Top)"},  // 048f2d42-772d-4c34-a94c-dacba2c67749
    {0x4BA586A8C37C5AF4ULL, 0x4A3C8F6C74B5FF87ULL, "S Completion Rank"},  // c37c5af4-86a8-4ba5-87ff-b5746c8f3c4a
    {0x4C608D01E46C8D0FULL, 0x4B6698E7B4CC1181ULL, "Annette Birkin"},  // e46c8d0f-8d01-4c60-8111-ccb4e798664b
    {0x40BC3C961EEB8941ULL, 0x4BB1BD2783AC7B83ULL, "W-870"},  // 1eeb8941-3c96-40bc-837b-ac8327bdb14b
    {0x41D7C409D2B206B0ULL, 0x4BE3484EAD9ECEBDULL, "Sewers"},  // d2b206b0-c409-41d7-bdce-9ead4e48e34b
    {0x4EF74A6724573568ULL, 0x4D69F90D35F2D496ULL, ".50 AE MAG (Chief's?)"},  // 24573568-4a67-4ef7-96d4-f2350df9694d
    {0x4CB58B9175AF936BULL, 0x4F0624BCEE112EB8ULL, "JMB Hp3"},  // 75af936b-8b91-4cb5-b82e-11eebc24064f
    {0x4AD79318F215A85AULL, 0x564B555D20FB7D86ULL, "Early Key Visual"},  // f215a85a-9318-4ad7-867d-fb205d554b56
    {0x4E03AC1ECF7D2648ULL, 0x56757315FD21F889ULL, "Orphanage"},  // cf7d2648-ac1e-4e03-89f8-21fd15737556
    {0x488F4256CC7337D3ULL, 0x5744BE0416C5959EULL, "Leon (Alternative)"},  // cc7337d3-4256-488f-9e95-c51604be4457
    {0x4D521F48AEFF7EF8ULL, 0x58BF0B76D49FEDB0ULL, "G (Stage 5)"},  // aeff7ef8-1f48-4d52-b0ed-9fd4760bbf58
    {0x4E88CE92FF94EE0BULL, 0x5B7D35A3B7B5AB85ULL, "Hunk"},  // ff94ee0b-ce92-4e88-85ab-b5b7a3357d5b
    {0x4F0BD54343275DEFULL, 0x5F24C7AC138F3D9EULL, "Broom Hc"},  // 43275def-d543-4f0b-9e3d-8f13acc7245f
    {0x481CB4A82250AC08ULL, 0x604C43281E7ECEBAULL, "M19"},  // 2250ac08-b4a8-481c-bace-7e1e28434c60
    {0x4E2D88373FA92F0AULL, 0x65390E1682D980BBULL, "Samurai Edge (Albert Model)"},  // 3fa92f0a-8837-4e2d-bb80-d982160e3965
    {0x4916C10C582FEB7BULL, 0x6A66B1C49BA50E85ULL, "Raccoon City B"},  // 582feb7b-c10c-4916-850e-a59bc4b1666a
    {0x42CFA721A8EEC18AULL, 0x6B8279B8C4CEEAA6ULL, "Claire (Classic Tank Top)"},  // a8eec18a-a721-42cf-a6ea-cec4b879826b
    {0x44895716453EEE34ULL, 0x6BD30F616762F88DULL, "Acid Rounds"},  // 453eee34-5716-4489-8df8-6267610fd36b
    {0x418798C08BF7F134ULL, 0x6CD38E665994A7B0ULL, "ATM-4"},  // 8bf7f134-98c0-4187-b0a7-9459668ed36c
    {0x41C659B547E5B5CFULL, 0x6D76FD2EA3CC8AB6ULL, "Lab A"},  // 47e5b5cf-59b5-41c6-b68a-cca32efd766d
    {0x42C9F08EA736723AULL, 0x6EFE18729C5F5C8EULL, "Licker"},  // a736723a-f08e-42c9-8e5c-5f9c7218fe6e
    {0x4F2C4D4BC6841378ULL, 0x726E5DE09E10A3A8ULL, "Magic Upgrade Gun (Temp)"},  // c6841378-4d4b-4f2c-a8a3-109ee05d6e72
    {0x494E1C1F3C904E16ULL, 0x733626BC381CE49EULL, "Lab B"},  // 3c904e16-1c1f-494e-9ee4-1c38bc263673
    {0x43A0DE25FFAD12BEULL, 0x776F31B2AA76E2A5ULL, "The Tofu Survivor (Konjac unlocked)"},  // ffad12be-de25-43a0-a5e2-76aab2316f77
    {0x4210374DB8B0BFA9ULL, 0x7A1F1033CE2690A4ULL, "W-870"},  // b8b0bfa9-374d-4210-a490-26ce33101f7a
    {0x4090B42C0C10EFE6ULL, 0x7AD8D1AC2A368F9BULL, "ATM-4"},  // 0c10efe6-b42c-4090-9b8f-362aacd1d87a
    {0x4DEA71AAAF7910AFULL, 0x7AF2881605BFDA9CULL, "ATM-4"},  // af7910af-71aa-4dea-9cda-bf051688f27a
    {0x4A9E3344AACEFBE4ULL, 0x7F5B8A4E268811B5ULL, "Claire (Jacket)"},  // aacefbe4-3344-4a9e-b511-88264e8a5b7f
    {0x4A8CAA632516D8B7ULL, 0x80EB64BC0AC87985ULL, "MUP"},  // 2516d8b7-aa63-4a8c-8579-c80abc64eb80
    {0x4B8A5E4E73FDE8BEULL, 0x82EADE7CF51D6A84ULL, "Ivy"},  // 73fde8be-5e4e-4b8a-846a-1df57cdeea82
    {0x42B9C4070AD8351AULL, 0x84BD9F4E464168BBULL, "Combat Knife"},  // 0ad8351a-c407-42b9-bb68-41464e9fbd84
    {0x471B22933EC30FBEULL, 0x84EC566F9FDA20AAULL, "Sherry (Classic School Uniform)"},  // 3ec30fbe-2293-471b-aa20-da9f6f56ec84
    {0x46936BA192C09A0BULL, 0x859B463A177A3FB8ULL, "Claire (Alternative)"},  // 92c09a0b-6ba1-4693-b83f-7a173a469b85
    {0x4B7DBB3BF497B0A2ULL, 0x887244F4160F659AULL, "Normal Bolt"},  // f497b0a2-bb3b-4b7d-9a65-0f16f4447288
    {0x412AD33DC1D747E5ULL, 0x8B07AEE4F431E3ABULL, "Tofu"},  // c1d747e5-d33d-412a-abe3-31f4e4ae078b
    {0x4125D8723F679DA0ULL, 0x8BCD5EDC71792D82ULL, "Quickdraw Army"},  // 3f679da0-d872-4125-822d-7971dc5ecd8b
    {0x45CCB5C56666D46DULL, 0x8BECC6B1A41B8B8EULL, "Grenade"},  // 6666d46d-b5c5-45cc-8e8b-1ba4b1c6ec8b
    {0x4362FAA217F63A91ULL, 0x8D3F54E5BDA43694ULL, "Lightning Hawk"},  // 17f63a91-faa2-4362-9436-a4bde5543f8d
    {0x4CD29BFD3598FB63ULL, 0x8D98B53957472694ULL, "G (Stage 3)"},  // 3598fb63-9bfd-4cd2-9426-475739b5988d
    {0x41E81C6C21AB1BBDULL, 0x8DA45367C5284597ULL, "Samurai Edge (Original Model)"},  // 21ab1bbd-1c6c-41e8-9745-28c56753a48d
    {0x4669BF1FC8003804ULL, 0x8F517CC61545E3A9ULL, "Marvin Branagh"},  // c8003804-bf1f-4669-a9e3-4515c67c518f
    {0x49F3A62C6A1B1404ULL, 0x8F69AB98B5F60A96ULL, "GM 79"},  // 6a1b1404-a62c-49f3-960a-f6b598ab698f
    {0x4496775C231984E1ULL, 0x98149139D3B6F0B8ULL, "Bonus 1"},  // 231984e1-775c-4496-b8f0-b6d339911498
    {0x4F40188506058055ULL, 0x9AFB72E40F3776BAULL, "Zombie Dog"},  // 06058055-1885-4f40-ba76-370fe472fb9a
    {0x499E1107DD9AC41FULL, 0x9E2FD730F8BF3EADULL, "\"Hardcore\" Game Mode"},  // dd9ac41f-1107-499e-ad3e-bff830d72f9e
    {0x4AD3EB64722B0ADEULL, 0xA0D4F05BCCBE5989ULL, "Matilda"},  // 722b0ade-eb64-4ad3-8959-becc5bf0d4a0
    {0x4A9B1A9ABAD889A0ULL, 0xA15502265FDE36A6ULL, "Police Station C"},  // bad889a0-1a9a-4a9b-a636-de5f260255a1
    {0x40180C3256AD64C5ULL, 0xA1D2758D3C464C81ULL, "Claire [2nd] Story Mode"},  // 56ad64c5-0c32-4018-814c-463c8d75d2a1
    {0x4127DD3B556D6D9FULL, 0xA376EC85D08127BFULL, "Ada (Normal Custom)"},  // 556d6d9f-dd3b-4127-bf27-81d085ec76a3
    {0x45518210FDF32068ULL, 0xA3DD32FFCF265291ULL, "The Tofu Survivor (Annin Tofu unlocked)"},  // fdf32068-8210-4551-9152-26cfff32dda3
    {0x40EDA02DFC1CDCC3ULL, 0xA68020A625D7CBBCULL, "Bonus 4 (Melee)"},  // fc1cdcc3-a02d-40ed-bccb-d725a62080a6
    {0x43E0788C3F8A28FAULL, 0xA770AA76CBB0FDBFULL, "Zombie"},  // 3f8a28fa-788c-43e0-bffd-b0cb76aa70a7
    {0x4F3A12AC482E321FULL, 0xAAB57DF92C08449DULL, "G-Adult"},  // 482e321f-12ac-4f3a-9d44-082cf97db5aa
    {0x4BB45819911C2354ULL, 0xAC20989C54E580BFULL, "Uiro-Mochi"},  // 911c2354-5819-4bb4-bf80-e5549c9820ac
    {0x481438BD894A64ADULL, 0xB22B27697B4811B6ULL, "G (Stage 1)"},  // 894a64ad-38bd-4814-b611-487b69272bb2
    {0x4C153BB91564A212ULL, 0xB2AEE97237B63E91ULL, "Ada (Cocktail Dress)"},  // 1564a212-3bb9-4c15-913e-b63772e9aeb2
    {0x43DA4B92E156E632ULL, 0xB2B3C2571D8E909FULL, "Sherry (Normal Custom)"},  // e156e632-4b92-43da-9f90-8e1d57c2b3b2
    {0x4F42F4B4CF4C447CULL, 0xB3AA23CBAFA350BEULL, "William Birkin"},  // cf4c447c-f4b4-4f42-be50-a3afcb23aab3
    {0x4E476AF339555E98ULL, 0xB4152E013BAB35A8ULL, "Raccoon City A"},  // 39555e98-6af3-4e47-a835-ab3b012e15b4
    {0x43E4B0C5EE572BFEULL, 0xB70081D00F6DDA86ULL, "Sherry (Jacket)"},  // ee572bfe-b0c5-43e4-86da-6d0fd08100b7
    {0x477006AB7B3124E4ULL, 0xB91759671F5BC18CULL, "Police Station D"},  // 7b3124e4-06ab-4770-8cc1-5b1f675917b9
    {0x4FF870F57D79E23AULL, 0xB94ECFC5720735BBULL, "G (Stage 4)"},  // 7d79e23a-70f5-4ff8-bb35-0772c5cf4eb9
    {0x4BAE10EF42339E62ULL, 0xBADA48EC695D8495ULL, "Samurai Edge (Original Model)"},  // 42339e62-10ef-4bae-9584-5d69ec48daba
    {0x42843322A245556CULL, 0xBB2ED4D3C2CC6296ULL, "EMF Visualizer"},  // a245556c-3322-4284-9662-ccc2d3d42ebb
    {0x4B172611751422C7ULL, 0xBC386AB1FC71A5BCULL, "Minigun"},  // 751422c7-2611-4b17-bca5-71fcb16a38bc
    {0x4DA81686311B63EBULL, 0xC2EBFC6328747088ULL, "Mine Bolt"},  // 311b63eb-1686-4da8-8870-742863fcebc2
    {0x46B74FC04B5E3753ULL, 0xC3659BCEB4F0ABA8ULL, "SLS 60"},  // 4b5e3753-4fc0-46b7-a8ab-f0b4ce9b65c3
    {0x42F0E62B97A880A7ULL, 0xC96B5F342BF87EBEULL, "G (Stage 1)"},  // 97a880a7-e62b-42f0-be7e-f82b345f6bc9
    {0x482495F4913020A0ULL, 0xCB38637BFEF5F79FULL, "Zombie (Female)"},  // 913020a0-95f4-4824-9ff7-f5fe7b6338cb
    {0x4769B0162039A156ULL, 0xCD7586359760B997ULL, "Sherry (School Uniform - Infected version)"},  // 2039a156-b016-4769-97b9-6097358675cd
    {0x46D946E0A345BDE4ULL, 0xCE60F53D9CA80C86ULL, "Konjac"},  // a345bde4-46e0-46d9-860c-a89c3df560ce
    {0x49A29442A417F3A3ULL, 0xCEB77DEAA1756A8EULL, "Katherine Warren"},  // a417f3a3-9442-49a2-8e6a-75a1ea7db7ce
    {0x4C9360800B1E7AF4ULL, 0xD380C6080CE1809AULL, "Logos and Icons"},  // 0b1e7af4-6080-4c93-9a80-e10c08c680d3
    {0x4A02DD293CDC66F8ULL, 0xD4174344FBBB30ABULL, "Spark Shot"},  // 3cdc66f8-dd29-4a02-ab30-bbfb444317d4
    {0x44C6BB6E57128582ULL, 0xD569A3D2BB6083BEULL, "Giant Roach"},  // 57128582-bb6e-44c6-be83-60bbd2a369d5
    {0x4824496EED9E270EULL, 0xD9D4A34A9AF355AFULL, "Matilda"},  // ed9e270e-496e-4824-af55-f39a4aa3d4d9
    {0x4BCA452F4C348B0FULL, 0xD9EECB6947D4A7A0ULL, "Super Tyrant"},  // 4c348b0f-452f-4bca-a0a7-d44769cbeed9
    {0x4736F9A5346D5C77ULL, 0xE0E6909EC12CF095ULL, "Grenade Rounds"},  // 346d5c77-f9a5-4736-95f0-2cc19e90e6e0
    {0x40332BD96C0FD8DAULL, 0xE11D6C4C2B0787ABULL, "Samurai Edge (Jill Model)"},  // 6c0fd8da-2bd9-4033-ab87-072b4c6c1de1
    {0x49A256D482C467DBULL, 0xE197CEA712995F83ULL, "G (Stage 5)"},  // 82c467db-56d4-49a2-835f-9912a7ce97e1
    {0x4541C791E696A97CULL, 0xE212EF50442BF39CULL, "Leon (Police)"},  // e696a97c-c791-4541-9cf3-2b4450ef12e2
    {0x4181211626114360ULL, 0xE2D80142DBF8E9AEULL, "Leon (Normal Custom)"},  // 26114360-2116-4181-aee9-f8db4201d8e2
    {0x4348037552E24DF1ULL, 0xE34FDC3246C9AB8EULL, "Raccoon City D"},  // 52e24df1-0375-4348-8eab-c94632dc4fe3
    {0x4B7C32000BAF3AC6ULL, 0xE38716F6058379A3ULL, "G (Stage 3)"},  // 0baf3ac6-3200-4b7c-a379-8305f61687e3
    {0x4767F7D3C446B934ULL, 0xE426A5EE59C0BC8AULL, "Leon (Classic Police)"},  // c446b934-f7d3-4767-8abc-c059eea526e4
    {0x4C876703D301FA97ULL, 0xE5556E7C9EB732B6ULL, "Sherry (Classic Custom)"},  // d301fa97-6703-4c87-b632-b79e7c6e55e5
    {0x49D34AC29738C427ULL, 0xE68AD8BFDBBD8A9CULL, "Minigun"},  // 9738c427-4ac2-49d3-9c8a-bddbbfd88ae6
    {0x4CCD27A22E1E4232ULL, 0xE7418793FCC00F92ULL, "Claire (Classic Custom)"},  // 2e1e4232-27a2-4ccd-920f-c0fc938741e7
    {0x46B46152A5C3E8D3ULL, 0xE8B500A9877459A4ULL, "EMF Visualizer"},  // a5c3e8d3-6152-46b4-a459-7487a900b5e8
    {0x45BCC49EDE0B991DULL, 0xECB32967EBE52AB8ULL, "Combat Knife"},  // de0b991d-c49e-45bc-b82a-e5eb6729b3ec
    {0x4554E1A11F680F61ULL, 0xECE1091374CDEBA2ULL, "Combat Knife"},  // 1f680f61-e1a1-4554-a2eb-cd741309e1ec
    {0x48095A793B7E00C8ULL, 0xED7684AB5FA059A2ULL, "Chemical Flamethrower"},  // 3b7e00c8-5a79-4809-a259-a05fab8476ed
    {0x4C6629A83D3CD5CDULL, 0xEDDA925E66212CA7ULL, "LE 5"},  // 3d3cd5cd-29a8-4c66-a72c-21665e92daed
    {0x4E3FE23447440693ULL, 0xF0B34CC4FB886A98ULL, "Broom Hc"},  // 47440693-e234-4e3f-986a-88fbc44cb3f0
    {0x4BFE62F64A68B099ULL, 0xF26E60CFD180A6B2ULL, "Bonus 2"},  // 4a68b099-62f6-4bfe-b2a6-80d1cf606ef2
    {0x41FA23000EDF4703ULL, 0xF31547E953D061A1ULL, "Hand Grenade"},  // 0edf4703-2300-41fa-a161-d053e94715f3
    {0x4B70749EE0306C7DULL, 0xF465CF849CF254AEULL, "Design Sketch A"},  // e0306c7d-749e-4b70-ae54-f29c84cf65f4
    {0x49D5D3B7BC8153B4ULL, 0xF46BB89CDB6656B4ULL, "G (Stage 4)"},  // bc8153b4-d3b7-49d5-b456-66db9cb86bf4
    {0x44080EC5580E82A8ULL, 0xF68ACEF3BA1CD5BCULL, "MUP"},  // 580e82a8-0ec5-4408-bcd5-1cbaf3ce8af6
    {0x451FC4D30ACE8340ULL, 0xFD42C9D451BBD680ULL, "Samurai Edge (Chris Model)"},  // 0ace8340-c4d3-451f-80d6-bb51d4c942fd
    {0x42D9DEBAECD770FEULL, 0xFDAD30FE6BE3D2B7ULL, "Design Sketch C"},  // ecd770fe-deba-42d9-b7d2-e36bfe30adfd
    {0x41817930727400F2ULL, 0xFE594F7D3943D5AEULL, "Mr. Raccoon"},  // 727400f2-7930-4181-aed5-43397d4f59fe
    {0x4EA53B98BC93D2D3ULL, 0xFF6D090744251BAAULL, "Leon [2nd] Story Mode"},  // bc93d2d3-3b98-4ea5-aa1b-254407096dff
};

}  // namespace re2cc::records_text
